import { ITheme } from './types';

export enum ColorsEnum {
  WHITE = '#FFFFFF',
  BLACK = '#000000',
  CHARCOAL = '#4C4C4B',
  GRAY = '#E0E0E0',
  BRONZED = '#B78E80',
  ROSEY = '#DFB2A9',
  BEIGE = '#F3DED7',
  PINK = '#E89B93',
  LIGHT_PINK = '#FFDAE9',
  CRIMSON = '#DC143C',
}

export const theme: ITheme = {
  colors: {
    WHITE: ColorsEnum.WHITE,
    BLACK: ColorsEnum.BLACK,
    CHARCOAL: ColorsEnum.CHARCOAL,
    GRAY: ColorsEnum.GRAY,
    BRONZED: ColorsEnum.BRONZED,
    ROSEY: ColorsEnum.ROSEY,
    BEIGE: ColorsEnum.BEIGE,
    PINK: ColorsEnum.PINK,
    LIGHT_PINK: ColorsEnum.LIGHT_PINK,
    CRIMSON: ColorsEnum.CRIMSON,
  },
  fontWeights: {
    xxs: 200,
    xs: 300,
    s: 400,
    m: 500,
    l: 600,
    xl: 700,
  },
  fontSizes: {
    xxs: 14,
    xs: 16,
    sss: 18,
    ss: 22,
    s: 26,
    m: 30,
    mm: 32,
    mmm: 40,
    l: 63,
    ll: 66,
    xl: 70,
  },
  fontFamilies: {
    cinzelDecorative: '`Cinzel Decorative`, sans-serif',
    tangerine: '`Tangerine`, sans-serif',
    cormorant: '`Cormorant`, sans-serif',
  },
  width: {
    pr50: 50,
    xxs: 25,
    xs: 70,
    s: 100,
    ss: 130,
    ssss: 180,
    ssm: 200,
    ssmm: 250,
    sm: 330,
    smm: 365,
    smmm: 400,
    sss: 480,
    m: 500,
    mm: 750,
    l: 1280,
  },
  height: {
    xxs: 12,
    xss: 24,
    xs: 52,
    ss: 58,
    sm: 80,
    s: 110,
    m: 330,
    l: 420,
    xl: 484,
  },
  margins: {
    xxxs: 0,
    xxs: 15,
    xs: 25,
    s: 50,
  },
  paddings: {
    xxxs: 0,
    xxs: 8,
    xs: 25,
  },
  borders: {
    xxs: 1,
    xs: 4,
    s: 6,
  },
  borderRadiuses: {
    s: 8,
    m: 30,
    l: 50,
  },
  opacities: {
    s: 0.2,
    m: 0.5,
    l: 1,
  },
  zIndexes: {
    s: 1000,
    m: 2000,
  },
  gaps: {
    px10: 10,
    px20: 20,
  },
  top: {
    s: 100,
  },
  dimensions: {
    laptop: 1024,
  },
};
